### ISSUE TITLE
Stuck when making the second connection

### ISSUE THREAD

**Issue by Victrid** [Victrid/splatplost#1]
The first connection works fine, but it gets stuck when making the second connection.

**Comment by Victrid** [comment]
This is a known issue. 

It is because the second time the system connects it tries to connect using the already remembered Bluetooth option, and switch rejects the request with the wrong configuration.

You can temporarily solve this problem by "**forgetting the device**" in the system Bluetooth configuration.

This problem will be fixed later, so you won't need to do this.

**Comment by DaYu525** [comment]
It’s useful for me to turn off the android mobilephone bluetooth switch, because I used to use joycon droid app to emulate the nintendo switch controller, and it also try to connect to nintendo switch when I use this project in vm, so I close it to avoid phone's try. So I can easily reconnect now.

**Comment by Victrid** [comment]
This problem is fixed. If you still have this problem, please reopen this issue first.

**Comment by DaYu525** [comment]
ok &amp; thx ,&nbsp; I'll try it later




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jiang ***@***.***&gt;; 
发送时间: 2021年3月27日(星期六) 晚上7:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Victrid/splatplost] Stuck when making the second connection (#1)





 
This problem is fixed. If you still have this problem, please reopen this issue first.
