### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Charlie441324219** [Victrid/splatplost#2]
Error occured when running `python ./insgen.py IMAGE.png IMAGE.order`:
```
File "./insgen.py", line 131
    f"Complete. Original difficulty: {original_num}, Optimized difficulty:{optimized_num}\n")
                                                                                           ^
SyntaxError: invalid syntax
```

**Comment by DaYu525** [comment]
use python3

**Comment by Victrid** [comment]
Please use Python 3.6+. 
OS with lower versions of python3 is rare. This is commonly caused because some OS will use python2 as its default python intepreter, try substitute `python` with `python3` above before you installation. Python 2 has reached its end of life [since Jan 2020](https://www.python.org/doc/sunset-python-2/).

---
请使用Python 3.6+。
python版本这么低是很少见的，运行不了通常是因为有些操作系统会默认使用Python2作为python命令的默认解释器，在安python3前可以先将命令中的`python` 换为 `python3` 试试，说不定系统本身就带了Python 3。Python 2支持生命周期已经在2020年1月截止。
