### ISSUE TITLE
windows和虚拟机都试过了，都有相同的报错

### ISSUE THREAD

**Issue by tangio** [Victrid/splatplost#8]
root@t-virtual-machine:/home/t/下载/splatplost-master# python ./print.py IMAGE.order
Traceback (most recent call last):
File "./print.py", line 11, in <module>
from joycontrol.controller_state import ControllerState, button_push, button_press, button_release
File "/home/t/下载/splatplost-master/joycontrol/controller_state.py", line 3, in <module>
from joycontrol import utils
File "/home/t/下载/splatplost-master/joycontrol/utils.py", line 5, in <module>
import hid
File "/usr/local/lib/python3.6/dist-packages/hid/__init__.py", line 30, in <module>
raise ImportError(error)
ImportError: Unable to load any of the following libraries:libhidapi-hidraw.so libhidapi-hidraw.so.0 libhidapi-libusb.so libhidapi-libusb.so.0 libhidapi-iohidmanager.so libhidapi-iohidmanager.so.0 libhidapi.dylib hidapi.dll libhidapi-0.dll

https://bbs.nga.cn/read.php?&tid=25779071&pid=632631776&to=1

**Comment by FallenMeteorite** [comment]
sudo apt install libhidapi-dev
and it can be imported

**Comment by FallenMeteorite** [comment]
sudo apt install libhidapi-dev
and it can be imported

**Comment by Victrid** [comment]
Hello, 
Your problem is addressed at https://github.com/Victrid/splatplost/issues/11. This will be fixed recently and please notice those issues for further updates.
I'll close this issue for now. If you have further problems, just reopen this issue.

---

你好。
您的问题已在 https://github.com/Victrid/splatplost/issues/11 中提及。这将在最近得到解决，请注意这些问题，以便进一步更新。
我将暂时关闭这个问题。如果你有进一步的问题，就重新打开这个问题。
